# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/monitor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14protos/monitor.proto\x12\x07monitor\"U\n\nMetricData\x12\x10\n\x08hostname\x18\x01 \x01(\t\x12\x13\n\x0bmetric_type\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x01\"/\n\x0e\x43ommandRequest\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x02 \x01(\t2S\n\x0eMonitorService\x12\x41\n\rCommandStream\x12\x13.monitor.MetricData\x1a\x17.monitor.CommandRequest(\x01\x30\x01\x62\x06proto3')



_METRICDATA = DESCRIPTOR.message_types_by_name['MetricData']
_COMMANDREQUEST = DESCRIPTOR.message_types_by_name['CommandRequest']
MetricData = _reflection.GeneratedProtocolMessageType('MetricData', (_message.Message,), {
  'DESCRIPTOR' : _METRICDATA,
  '__module__' : 'protos.monitor_pb2'
  # @@protoc_insertion_point(class_scope:monitor.MetricData)
  })
_sym_db.RegisterMessage(MetricData)

CommandRequest = _reflection.GeneratedProtocolMessageType('CommandRequest', (_message.Message,), {
  'DESCRIPTOR' : _COMMANDREQUEST,
  '__module__' : 'protos.monitor_pb2'
  # @@protoc_insertion_point(class_scope:monitor.CommandRequest)
  })
_sym_db.RegisterMessage(CommandRequest)

_MONITORSERVICE = DESCRIPTOR.services_by_name['MonitorService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _METRICDATA._serialized_start=33
  _METRICDATA._serialized_end=118
  _COMMANDREQUEST._serialized_start=120
  _COMMANDREQUEST._serialized_end=167
  _MONITORSERVICE._serialized_start=169
  _MONITORSERVICE._serialized_end=252
# @@protoc_insertion_point(module_scope)
